on: [push]

name: Code Coverage

jobs:
  tarpaulin-codecov:
    name: Tarpaulin to codecov.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set default toolchain
        run: rustup default nightly
      - name: Set profile
        run: rustup set profile minimal

      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Tarpaulin
        run: cargo tarpaulin --features all-keys,cli-utils,compiler,esplora,compact_filters --run-types Tests,Doctests --exclude-files "testutils/*"

      - name: Publish to codecov.io
        uses: codecov/codecov-action@v1.0.14
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
